### ISSUE TITLE
 module 'cv2.cv2' has no attribute 'TrackerKCF_create'

### ISSUE THREAD

**Issue by wwdok** [apoorvavinod/Real_time_Object_detection_and_tracking#22]
I downloaded the repo, and then run the command `python src/main.py --model model_data/MobileNetSSD_deploy.caffemodel --config model_data/MobileNetSSD_deploy.prototxt --classes model_data/MobileNet_classes.txt --input "C:/MachineLearning/CV/Object_Tracking/video2.mp4"`, but the result is the window shows up for one second, then flash away, and the command prompt printed out following error:
```
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects []
Tracking -  []
Tracking the following objects ['motorbike_0']
Traceback (most recent call last):
  File "src/main.py", line 268, in <module>
    main()
  File "src/main.py", line 265, in main
    process(args)
  File "src/main.py", line 211, in process
    stream, objects_detected, objects_list, trackers_dict = intermediate_detections(stream, predictor, args.thr, classes)
  File "src/main.py", line 110, in intermediate_detections
    trackers_dict = {key : cv.TrackerKCF_create() for key in objects_list}
  File "src/main.py", line 110, in <dictcomp>
    trackers_dict = {key : cv.TrackerKCF_create() for key in objects_list}
AttributeError: module 'cv2.cv2' has no attribute 'TrackerKCF_create'
```
Here is the video : https://streamja.com/0PZPG

**Comment by apoorvavinod** [comment]
Please go refer previously closed issues. This is opencv installation issue.
